import type { Metadata } from "next";

import "../assets/css/globals.css";

import { Roboto_Mono } from 'next/font/google';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={robotoMono.className}>
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
