import type { Metadata } from "next";

import "../assets/css/globals.css";

import { Roboto_Mono } from "next/font/google";

import Header from "../app/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br" className={robotoMono.className}>
      <body>
        <div className="custom-container">
          <Header />

          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
